#!/bin/bash

echo ""
echo "========================================"
echo "   VIB34D DEMO LAUNCHER"
echo "========================================"
echo ""
echo "Starting Python HTTP Server on port 8000..."
echo ""
echo "Once the server starts, open these URLs in your browser:"
echo ""
echo "1. MAIN DEMO (8 Visualizers):"
echo "   http://localhost:8000/VIB34D_PHASE1_INTEGRATED_DEMO.html"
echo ""
echo "2. PARAMETER TESTING:"
echo "   http://localhost:8000/VIB34D_PARAMETER_VERIFICATION_SYSTEM.html"
echo ""
echo "3. END-TO-END CASCADE TEST:"
echo "   http://localhost:8000/VIB34D_END_TO_END_CASCADE_TEST.html"
echo ""
echo "Press Ctrl+C to stop the server when done."
echo "========================================"
echo ""
python3 -m http.server 8000